/**
 * Migration: Expands the auth_verifications.target_type CHECK constraint to
 * include 'password_reset', enabling the forgot-password OTP flow to reuse
 * the existing table without creating separate infrastructure.
 *
 * The constraint is dropped and recreated because PostgreSQL does not support
 * ALTER CONSTRAINT on CHECK constraints — the standard approach is
 * DROP + ADD CONSTRAINT.
 *
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 */
exports.up = (pgm) => {
  // Drop the existing check constraint (name generated by node-pg-migrate from
  // the inline `check` option in the original migration).
  pgm.sql(`
    ALTER TABLE auth_verifications
      DROP CONSTRAINT IF EXISTS auth_verifications_target_type_check
  `);

  // Re-add with the extended value list.
  pgm.sql(`
    ALTER TABLE auth_verifications
      ADD CONSTRAINT auth_verifications_target_type_check
      CHECK (target_type IN ('email', 'phone', 'password_reset'))
  `);
};

/**
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 */
exports.down = (pgm) => {
  // Remove any password_reset rows first to avoid violating the narrower
  // constraint on rollback.
  pgm.sql(`DELETE FROM auth_verifications WHERE target_type = 'password_reset'`);

  pgm.sql(`
    ALTER TABLE auth_verifications
      DROP CONSTRAINT IF EXISTS auth_verifications_target_type_check
  `);

  pgm.sql(`
    ALTER TABLE auth_verifications
      ADD CONSTRAINT auth_verifications_target_type_check
      CHECK (target_type IN ('email', 'phone'))
  `);
};
